### ISSUE TITLE
Screenshots are weirdly cropped

### ISSUE THREAD

**Issue by dariuszteooh** [uktrade/cypress-image-diff#32] opened 2021-06-22 12:58 UTC
Hi folks, 

I'm trying to use the library to run image comparison tests, but the screenshots I'm getting are rather weirdly cropped. 
For example, this is what my page looks normally in the browser: 
![Screenshot 2021-06-22 at 13-55-35 Roomkey - Download](https://user-images.githubusercontent.com/64851760/122928304-a34db780-d361-11eb-92ad-edc07c26b844.png)
But the snapshot taken by your library looks like this: 
![visual_regression_tests-download-page](https://user-images.githubusercontent.com/64851760/122928364-b3659700-d361-11eb-94ad-fb167cb1b361.png)
As you can see, the viewport is very narrow and weirdly cropped. I'm running the tests headless. 
Tried Chrome and Firefox, no difference. I am settings the viewport manually in my tests:
`cy.viewport(1920, 1080)`
but it doesn't seem to have any effect. 
I'd appreciate any help with this. 

Thanks.

**Comment by davidicus** [comment] 2021-07-01 15:05
@dariuszteooh I noticed this as well. Have you found a solution?

**Comment by PippoRaimondi** [comment] 2021-07-05 21:57
it seems like the resolution of the browser is causing the issue. If you have a public facing website that you could give me to try some things, I can try to figure out exactly what's going on and possibly come up with a workaround.

**Comment by dariuszteooh** [comment] 2021-07-09 13:52
@PippoRaimondi try roomkey.co

**Comment by PippoRaimondi** [comment] 2021-07-14 16:23
Ok, will check tomorrow and let you know if there is a workaround.

**Comment by PippoRaimondi** [comment] 2021-07-26 10:00
sorry all, I was fighting covid so was down for a couple of weeks... will get to this task soon.

**Comment by PippoRaimondi** [comment] 2021-07-27 16:15
@dariuszteooh 

I ran the tests via docker, and ensured that both viewport size and docker display config was large: I.E

On cypress test:

```
  beforeEach(() => {
    cy.viewport(2560, 1440)
  })
```

On docker file:

```
ENV DISPLAY_CONFIGURATION=2560x1440x24
```

The config above resulted in the below screenshot, which IMO is acceptable. So I would say the issue is related to setup rather than the tool itself... I will give a couple of days until I close this issue off. Please let me know if you need help sorting out your config.

![test-spec-wholePage](https://user-images.githubusercontent.com/5696857/127189652-c2b457fd-4548-48d5-b040-61b06ac90bb4.png)

**Closed** 2021-08-05 09:11 UTC
