### ISSUE TITLE
dependecies only for cypress ^9.0.0

### ISSUE THREAD

**Issue by Mike1692** [uktrade/cypress-image-diff#59] opened 2021-12-01 10:50 UTC
Would be nice to have the dependencies also for cypress ^8.5.0. 
Now our pipe tries always install the new cypress version what causes some errors.

 "^8.5.0 || ^9.0.0" would be fine.

**Comment by PippoRaimondi** [comment] 2021-12-01 12:17
For now I would suggest using the last version available under 9.0.0:

https://github.com/uktrade/cypress-image-diff/releases/tag/v1.15.5

Another solution if this is causing a problem is to add resolution to your package, forcing your dependencies it to install whatever cypress version you'd like (should be used as last resort): https://www.npmjs.com/package/npm-force-resolutions...

I will study alternatives but I believe the above is the best we can do short term.

**Comment by albert-m-willemsen** [comment] 2022-09-08 10:40
seems a duplicate of [](https://github.com/uktrade/cypress-image-diff/issues/87)

**Comment by albert-m-willemsen** [comment] 2022-09-08 10:43
For the moment you can workaround using:
`  "overrides": {
    "cypress-image-diff-js": {
      "cypress": "$cypress"
    }
  }`
in your package.json

**Comment by PippoRaimondi** [comment] 2022-12-12 14:51
Solved in #89

**Closed by PippoRaimondi** 2022-12-12 14:51 UTC
